### ISSUE TITLE
[BUG] People - Manager POV - main view - Active tab 3dots menu wrong option name.

### ISSUE THREAD

**Issue by kellton-sarna** [Tivix/cpf#117]
**Actual result:**
After clicking on 3dots menu in Active tab user sees "Profile settings".

![Image](https://github.com/user-attachments/assets/183b0ff1-cfc2-44ff-8603-4f3e757e4465)

**Expected result:**
Should see "Manage account" [link](https://www.figma.com/design/B8kHltTqt6HZ8jR98qcPAe/CPF-design?node-id=314-26502&t=WX74J0dAn2QMWmPx-4)

**Relates to:**
https://github.com/Tivix/cpf/issues/36

**Comment by r1skz3ro** [comment]
@mczujowski same as before. I think we should add this functionality once real data is fetched and we can add 'manage account' functionality

**Comment by mczujowski** [comment]
https://github.com/orgs/Tivix/projects/11/views/1?pane=issue&itemId=72879277
