### ISSUE TITLE
[BUG] People - Manager POV - main view - Drafts tab 3dots menu has wrong option attached.

### ISSUE THREAD

**Issue by kellton-sarna** [Tivix/cpf#119]
**Actual result:**

![Image](https://github.com/user-attachments/assets/64d7fe96-db2f-448c-b3fa-be04e3be3c8d)

**Expected result:**
"3 Dots"- clicking it shows available options - "Delete user" [link](https://www.figma.com/design/B8kHltTqt6HZ8jR98qcPAe/CPF-design?node-id=382-38361&t=WX74J0dAn2QMWmPx-4)

**Relates to:**
https://github.com/Tivix/cpf/issues/36

**Comment by r1skz3ro** [comment]
@mczujowski it's the same case as #121. We can add this functionality once real data is fetched and we can delete a real user

**Comment by mczujowski** [comment]
It is replaced by this ticket: https://github.com/orgs/Tivix/projects/11/views/1?pane=issue&itemId=72879277
