### ISSUE TITLE
[BUG] People - Manager POV - main view - Deactivated tab 3dots menu has wrong options attached.

### ISSUE THREAD

**Issue by kellton-sarna** [Tivix/cpf#121]
**Actual result:**

![Image](https://github.com/user-attachments/assets/660117cd-8079-4e3a-95c5-20d20f8ea7c8)

**Expected result:**
"3 Dots" - clicking it shows available options - "Manage account", "Activate employee" [link](https://www.figma.com/design/B8kHltTqt6HZ8jR98qcPAe/CPF-design?node-id=382-38351&t=WX74J0dAn2QMWmPx-4)

**Relates to:**
https://github.com/Tivix/cpf/issues/36

**Comment by r1skz3ro** [comment]
This option should be changed when real data is fetched

**Comment by mczujowski** [comment]
Ok, I'll add a ticket for fetching data once it is implemented.

**Comment by mczujowski** [comment]
https://github.com/orgs/Tivix/projects/11/views/1?pane=issue&itemId=72879277
