### ISSUE TITLE
[BUG] People - Manager POV - main view - band dropdown filtering is missing hover effect.

### ISSUE THREAD

**Issue by kellton-sarna** [Tivix/cpf#122]
**Actual result:**
No hover effect.

![Image](https://github.com/user-attachments/assets/cb8684c9-447f-4582-9fb5-ea05d6c0bc4f)

**Expected result:**
The selected filter has a hover effect [link](https://www.figma.com/design/B8kHltTqt6HZ8jR98qcPAe/CPF-design?node-id=1129-213381&t=WX74J0dAn2QMWmPx-4)

**Relates to:**
https://github.com/Tivix/cpf/issues/36

**Comment by r1skz3ro** [comment]
After discussions with Valentina, we decided to tweak a few things a bit, here are the updated designs - https://www.figma.com/design/B8kHltTqt6HZ8jR98qcPAe/CPF-(Full-version)?node-id=1129-213381&t=H2sXjXvSWGrhLDmX-0
