### ISSUE TITLE
[Feature] CPF Library - An example way to pass level

### ISSUE THREAD

**Issue by skorekm** [Tivix/cpf#24]
### Requirements:
- According to the designs.
- Breadcrumbs are displayed at the top of the page. When the user clicks on the link, it is redirected to the given subpage.
- The examples of the way to pass the level are displayed in tables
- Each table has a title
- Each table contains rows with the specific project description or exemplary skills and their description required to pass the level.
- At the bottom of the screen, there is information such as: "Candidates should submit the code along with explanations for the design choices made. This task covers a broad range of programming concepts and will allow you to assess the candidate's proficiency in the specified skills."

### Tasks:
- [ ] FE
- [ ] BE

### Link to designs:
[Figma](https://www.figma.com/file/B8kHltTqt6HZ8jR98qcPAe/CPF-design?type=design&node-id=445-44428&mode=design&t=dksKoU8Ig3Pxa8RA-4)
[Clickable prorotype](https://www.figma.com/file/B8kHltTqt6HZ8jR98qcPAe/CPF-design?type=design&node-id=445-44448&mode=design&t=ZfBsgiibVUyB6xef-4)

**Comment by wiktoriasalamon** [comment]
@skorekm This seems outdated as we use a dialog with markdown to display a project overview.

**Comment by skorekm** [comment]
Correct, closing this issue. Thanks!
